//#include "/Users/pwl/git/readNews_remote/readLog/libText.jsx"
//#include "/Users/pwl/git/readNews_remote/readLog/ExportLayerCoordinatesToXML.jsx"
var _scriptPath= "/Users/pwl/Documents/Adobe Scripts/"
var _scriptPath = "C:\\Users\\wenhuake\\Documents\\Adobe Scripts\\"
#include "F:/Documents and Settings/Administrator/git/readNews_remote/readLog/libText.jsx"
#include "F:/Documents and Settings/Administrator/git/readNews_remote/readLog/ExportLayerCoordinatesToXML.jsx"
#include "F:/Documents and Settings/Administrator/git/readNews_remote/readLog/libc.jsx"
